### ISSUE TITLE
User Topic Count repeat on viewtopic

### ISSUE THREAD

**Issue by Galixte** [marttiphpbb/phpbb-ext-usertopiccount#3]
hi,

i have an issue, see that on my forum: http://www.ezcom-fr.com/download/file.php?id=120
The information text "Topics: xxx" is repeated.

**Comment by Galixte** [comment]
Hi @marttiphpbb,

could you take a look ?

**Comment by marttiphpbb** [comment]
What other extensions do you have installed? What happens when you switch them off? Which browser do you use?
Btw, note that the extension is far from ready. Topics are not counted correctly yet.

**Comment by Galixte** [comment]
Hi 

@marttiphpbb,

after many tests, it seems that the "Thanks for posts" extension from author rxu (https://www.phpbb.com/community/viewtopic.php?f=456&t=2259046 & https://github.com/rxu/thanks_for_posts) is the problem with your extension.

EDIT: i have also contacted rxu: https://github.com/rxu/thanks_for_posts/issues/33

**Comment by rxu** [comment]
The problem for this ext is that `Thanks for posts` ext uses `<dd class="profile-posts"` for injecting thanks info into viewtopic miniprofile which causes topics data to be inserted by JS in a loop.
While I'm going to update the TFP ext to use element class other than `profile-posts`, it would be making sense updating JS to avoid the [infinite] loop thing.

**Comment by Galixte** [comment]
Hi @marttiphpbb & @rxu,

About cIass `profile-posts` i propose this PR to fix it: https://github.com/rxu/thanks_for_posts/pull/38

After tests it seem be OK but i don't know what you say about "updating JS to avoid the  [infinite] loop thing".

About that "Btw, note that the extension is far from ready. Topics are not counted correctly yet" it's look like OK for me the count is good.

EDIT: in fact the count is not ok on viewtopic but it’s good on search topics page: https://www.phpbb.com/community/viewtopic.php?p=14097876#p14097876.

**Comment by Galixte** [comment]
Hi @marttiphpbb,

could you fix the error of infinite loop in JS that rxu has noted ?

**Comment by marttiphpbb** [comment]
When does the loop happen? I have the thanks for posts installed now but I don't see a loop.

**Comment by Galixte** [comment]
From files in https://github.com/marttiphpbb/phpbb-ext-usertopiccount/tree/master/styles/prosilver/template (profile.js or viewtopic.js maybe).

This bug (see my first post to see a screenshot) appears on topics with some messages and when the users have thanked or received some thanks (displayed in mini-profile on viewtopic).

**Comment by marttiphpbb** [comment]
So far I can't reproduce the issue. I've installed thanks-for-posts two days ago and I've multiple users and posts in one topic that have thanked each other multiple times but the issue doesn't occur both in Firefox (38.0) as well Chromium. (41.0.2272.76)

**Comment by rxu** [comment]
One more report https://www.phpbb.com/community/viewtopic.php?p=14110506#p14110506

After investigating a bit, I've found something that prevented repeating effect.
That's a small change to `viewtopic.js`:

``` js
$(this).insertBefore($(this).siblings('dd.profile-posts').eq(0));
```

In short, adding `.eq(0)` fixes the problem.

**Comment by marttiphpbb** [comment]
Merged. Thanks.

**Comment by Galixte** [comment]
Thanks @rxu !
