### ISSUE TITLE
General Error

### ISSUE THREAD

**Issue by 23grams** [marttiphpbb/phpbb-ext-usertopiccount#6]
Clean 3.2.2 install error when enabling extension:

`SQL ERROR [ mysqli ]

Unknown column 'u.user_topic_count' in 'having clause' [1054]

SQL

select count(t.topic_id) as topic_count, u.user_id from phpbb3_topics t, phpbb3_users u where t.topic_visibility = 1 and t.topic_poster = u.user_id and u.user_id >= 1 and u.user_id <= 47 and u.user_id <> 1 group by t.topic_poster having count(t.topic_id) <> u.user_topic_count

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 996
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/marttiphpbb/usertopiccount/service/update.php
LINE: 99
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/ext/marttiphpbb/usertopiccount/service/update.php
LINE: 122
CALL: marttiphpbb\usertopiccount\service\update->for_sql_where()

FILE: [ROOT]/ext/marttiphpbb/usertopiccount/ext.php
LINE: 69
CALL: marttiphpbb\usertopiccount\service\update->for_user_range()

FILE: [ROOT]/phpbb/extension/manager.php
LINE: 190
CALL: marttiphpbb\usertopiccount\ext->enable_step()

FILE: [ROOT]/includes/acp/acp_extensions.php
LINE: 209
CALL: phpbb\extension\manager->enable_step()

FILE: [ROOT]/includes/functions_module.php
LINE: 676
CALL: acp_extensions->main()

FILE: [ROOT]/adm/index.php
LINE: 82
CALL: p_master->load_active()`

**Comment by marttiphpbb** [comment]
I don't experience any problem on enabling. I am developing with the SQLite3 database however. 

[Link to issue in topic in phpbb.com](https://www.phpbb.com/community/viewtopic.php?f=456&t=2287936&p=15036696#p15036696)

**Comment by 23grams** [comment]
My apologies, should have stated:
MySQL(i) 10.3.7-MariaDB, nginx 1.13, php7.2.4.

**Comment by marttiphpbb** [comment]
I have updated this part in the code now and add the column only in the migrations. Version 0.3.0

**Comment by marttiphpbb** [comment]
https://www.phpbb.com/community/viewtopic.php?f=456&t=2287936&p=15037726#p15037726

Version 0.4.0

**Comment by 23grams** [comment]
0.4.0 allows enabling, thanks.
Will test this out over the next few days.
